repos:
  - repo: local
    hooks:
      - id: generate-library-init
        name: Generate library init
        entry: tools/library/gen_F.py
        language: python
        files: src/faebryk/library/_F.py
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format

