[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/faebryk/faebryk/issues "


[tool.poetry]
name = "faebryk"
version = "3.0.4"
authors = ["ioannis_iteng <ioannis@iteng.nl>"]
readme = ["README.md", "LICENSE"]
license = "MIT"
description = "Open-source software-defined EDA"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
repository = "https://github.com/faebryk/faebryk"
homepage = "https://github.com/faebryk/faebryk"

[tool.poetry.scripts]
faebryk = "faebryk.tools.main:__main__"

[tool.poetry.dependencies]
python = "^3.12,<3.13"                                # max allowed version by scipy
networkx = "3.3"
numpy = ">=1.24.3,<3.0.0"
scipy = "^1.11.1"
matplotlib = "^3.7.1"
sexpdata = "1.0.2"
black = "^24.4.2"
typing-extensions = "^4.6.3"
easyeda2kicad = "^0.8.0"
shapely = "^2.0.1"
freetype-py = "^2.4.0"
kicadcliwrapper = "^1.0.0"
dataclasses-json = "^0.6.7"
patool = "^2.3.0"
requests = "^2.32.3"
tortoise-orm = "^0.21.3"
rich = "^13.7.1"
typer = { version = ">=0.9,<0.13", extras = ["all"] }
isort = "^5.6.4"
ruff = ">=0.4.4,<0.6.0"
pint = "^0.24.3"

[tool.poetry.group.dev.dependencies]
pre-commit = ">=2.20,<4.0"
pytest = ">=7.1.3,<9.0.0"
viztracer = "^0.16.3"
pyinstrument = "^4.7.1"
gprof2dot = "^2024.6.6"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[tool.ruff]
line-length = 88         # Same as Black.
target-version = "py312"

[tool.ruff.format]
exclude = ["_F.py"]

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = [
    # Pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # Isort
    "I001",
]
ignore = [
    # Line too long
    #"E501",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "I",
    "N",
    "Q",
    "S",
    "T",
    "W",
    "ANN",
    "ARG",
    "BLE",
    "COM",
    "DJ",
    "DTZ",
    "EM",
    "ERA",
    "EXE",
    "FBT",
    "ICN",
    "INP",
    "ISC",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "SLF",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "YTT",
]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
